apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-backup-alerter
  namespace: longhorn-system
  labels:
    release: rancher-monitoring
spec:
  namespaceSelector:
    matchNames:
      - longhorn-system
  selector:
    matchLabels:
      app.kubernetes.io/name: longhorn-backup-alerter
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 15s
